apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 3
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: budget-app
          image: gautamjha3112002/test_web:0.21
          ports:
            - containerPort: 3000
          # env:   # Setting Enviornmental Variables
          #   - name: DB_HOST   # Setting Database host address from configMap
          #     valueFrom :
          #       configMapKeyRef :
          #         name : db-config
          #         key :  host

          #   - name: DB_NAME  # Setting Database name from configMap
          #     valueFrom :
          #       configMapKeyRef :
          #         name : db-config
          #         key :  dbName

          #   - name: DB_USERNAME  # Setting Database username from Secret
          #     valueFrom :
          #       secretKeyRef :
          #         name : mysql-secrets
          #         key :  username

          #   - name: DB_PASSWORD # Setting Database password from Secret
          #     valueFrom :
          #       secretKeyRef :
          #         name : mysql-secrets
          #         key :  password

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: budget-app-svc
spec:
  selector:
    app: postgres
  ports:
    - protocol: "TCP"
      port: 3000 # The port that the service is running on in the cluster
      targetPort: 3000 # The port exposed by the service
  type: NodePort # type of the service.