version: '3.7'
services:
  web:
    build: .
    ports:
      - "3000:3000"

    depends_on:
    - db
    
  db:
    image: postgres:12
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password1234


volumes:
  db-volume:
